### ISSUE TITLE
Site dead

### ISSUE THREAD

**Issue by davidcralph** [leeksapp/leeks-issues#2]
**Describe the bug**
Site is dead

**To Reproduce**
1. Just go to the fucking website
54645443536. See error

**Expected behavior**
Expected a working site that would give me my files (it's been like 6 months now)

**Screenshots**
you don't need a screenshot, look yourself.

**Desktop (please complete the following information):**
 - OS: WinDOS 10
 - Browser: Chrome Canary
 - Version: Broken

**Smartphone (please complete the following information):**
 - Device: Not an iphone
 - OS: android gang
 - Browser: chrome ofc
 - Version: idk

**Additional context**
fix it or i bearcop the general

**Comment by RoeeLupo** [comment]
no we won't because u not weeb

NYANNNNN CATTTTTT

**Comment by eartharoid** [comment]
💯

**Comment by davidcralph** [comment]
im weeb furry gang sir

**Comment by RoeeLupo** [comment]
OOF PLS NO BULLI ME 

NYANNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN CATTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT

**Comment by davidcralph** [comment]
bulli time

**Comment by sammy-ette** [comment]
cockonut

**Comment by RoeeLupo** [comment]
bastard!

**Comment by davidcralph** [comment]
h e c k

**Comment by RoeeLupo** [comment]
young bastard! I will call your mother right away!

**Comment by ohlookitsderpy** [comment]
https://derpyenterprises.org 

best site and do ``up arrow up arrow, down down, left right left right, b, a`` for kirbe mode

**Comment by mrsheldon** [comment]
https://mrsheldon.me

best site and do `n y a n` for nyan mode

**Comment by davidcralph** [comment]
hackerman

**Comment by auguwu** [comment]
this is gay shit

**Comment by davidcralph** [comment]
auguwu!!

**Comment by RoeeLupo** [comment]
NYANNNNNNNNN CATTTTTTTTTTT

**Comment by RoeeLupo** [comment]
auguwu!!! tell him you love nyan cat!!!

**Comment by auguwu** [comment]
kirb >>>>

**Comment by RoeeLupo** [comment]
ban

**Comment by davidcralph** [comment]
auguwu my man

**Comment by auguwu** [comment]
@ohlookitsderpy pls lewd me

**Comment by davidcralph** [comment]
lewd gang

**Comment by RoeeLupo** [comment]
auguwu u r not a weeb anymore!

**Comment by auguwu** [comment]
I will never be a furry/normie, both suck. weeb gang best

**Comment by davidcralph** [comment]
weeb gang innit

**Comment by RoeeLupo** [comment]
no, u r expelled from the weeb gang

**Comment by RoeeLupo** [comment]
error 2394247472384 isn't solved

**Comment by RoeeLupo** [comment]
I don't think we're getting anywhere

**Comment by davidcralph** [comment]
leeks issue board building up like

**Comment by RoeeLupo** [comment]
hackerman time

**Comment by RoeeLupo** [comment]
*hacking to leeks data center*

**Comment by RoeeLupo** [comment]
*aka raspberry pi 2*

**Comment by RoeeLupo** [comment]
*or $2.5 / mo vps at ovh*

**Comment by auguwu** [comment]
i have broken a rule (#3)

**Comment by RoeeLupo** [comment]
bad boye

**Comment by davidcralph** [comment]
you mean oXiDe HoStInG

**Comment by davidcralph** [comment]
overpriced shit

**Comment by davidcralph** [comment]
use like uhhh @Speyd3r dedi bc it fast

**Comment by duncte123** [comment]
Like you even care david
